#Try..Except

'''
number_1= int(input("Enter number :"))
number_2=int(input("Enter number :"))

result = number_1+number_2
print(result)

'''



'''
try:
    คำสั่งรันโปรแกรมปกติ
Except:
    คำสั่งทีทำงานตอนโปรแกรมมีข้้อผิดพลาด

'''
try:
    number_1= int(input("Enter number :"))
    number_2=int(input("Enter number :"))
    result = number_1+number_2
    print(result)
except:
    print("โปรแกรมมีข้อผิดพลาด")






